add_newline = true

format = """
[ î‚¶](fg:bright-cyan)$username[@](bg:bright-cyan fg:black)$hostname[î‚´](fg:bright-cyan)\
[ î‚¶](fg:bright-blue)$directory[î‚´](fg:bright-blue) \
$nix_shell\
$character
"""

right_format = """
$git_branch\
$git_status\
$deno\
$cmake\
$direnv\
$docker_context\
$c\
$lua\
$rust\
$golang\
$nodejs\
$python\
[î‚¶](fg:green)$cmd_duration[î‚´](fg:green)
"""

[username]
disabled            = false
show_always         = true
format              = "[$user]($style)"
style_user          = "fg:black bg:bright-cyan"

[hostname]
disabled            = false
ssh_only            = false
format              = "[$hostname]($style)"
style               = "fg:black bg:bright-cyan"

[directory]
format              = "[$path]($style)[$read_only]($read_only_style)"
repo_root_format    = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)[ ï ]($repo_root_style)"
read_only_style     = "fg:black bg:red"
repo_root_style     = "fg:black bg:bright-blue"
style               = "fg:black bg:bright-blue"
use_os_path_sep     = true

[cmd_duration]
format              = "[ï€— $duration]($style)"
style               = "fg:black bg:green"
show_milliseconds   = true
min_time            = 0

[character]
vicmd_symbol        = "[ğŸˆ](fg:yellow bold)"
success_symbol      = "[ğŸˆ](fg:green bold)"
error_symbol        = "[ğŸˆ](fr:red bold)"
